### ISSUE TITLE
Question on part selection for SMD capacitors

### ISSUE THREAD

**Issue by dburr** [johnwinans/2063-Z80#12]
Any reason in particular you chose 0603 parts for C17 and C24, yet went with an 0805 for C18? I, uh, may have accidentally lost the 0603 parts I ordered (tiny little buggers....and slippery too) and rather than wait for another Digikey order, I decided to try and shoehorn an 0805 part (which I had on hand) in place, and it fits!

Also, C18 is listed on the BOM as a polarized capacitor, and to my knowledge, SMD ceramic caps are unpolarized. Mistake, or is there some weird polarized SMD ceramic capacitor that I am unaware of?

**Comment by johnwinans** [comment]
I /should/ have used 0805 parts for all the surface mount to make it easier.  You can easily put an 0603 on an 0805 footprint, so it would have been easier to change the parts too.

I will leave this issue open until next time I tinker with this board and make this change.

Thanks for noticing!
