### ISSUE TITLE
Question on clock oscillator substitution

### ISSUE THREAD

**Issue by dburr** [johnwinans/2063-Z80#13]
Hello again,

Slowly getting together the parts for my Z80 Retro, but so far I still have not managed to find the 10 MHz crystal oscillator. It seems every time I check Digikey they are out of stock. However I do happen to have some 5 MHz oscillators left over from another project, and was wondering if I could use one of those instead, until such time as I am able to finally find the 10 MHz part. Aside from the system running at half the speed, would a slower clock cause any other negative effects (parts of the system to be unstable / not work, etc.)?

**Comment by johnwinans** [comment]
The Z80 can run at any speed up to the rated limit (and then some in many cases.)
5 MHz would be fine.  As you note, 9it will simply run slower.
