### ISSUE TITLE
Bad RAM part number?

### ISSUE THREAD

**Issue by zxMarce** [johnwinans/2063-Z80#15]
John, the silks on `2063.4.3` say `AS6C1008` (1MB) instead of `AS6C4008` (4MB) as the part number for the RAM chip. This can be (is?) kinda confusing.
The typo is also present in the 3D model picture in the main project page; noticed this while browsing parts to place an order.

On the other hand, the part itself is an AS6C4008 when checking the part's properties in KiCAD's PCB and schematic editors. Looks like just the silks are the only ones affected.

Marcelo.

**Comment by johnwinans** [comment]
You are absolutely right.  I'm on it.  :-(

**Comment by johnwinans** [comment]
Thanks.  Looks like it is time for a v4.3.1

**Comment by zxMarce** [comment]
Anytime. Glad it helped.
