### ISSUE TITLE
Allow alternate SD card sockets

### ISSUE THREAD

**Issue by johnwinans** [johnwinans/2063-Z80#3]
Due to the galactic parts-shortage, Digikey, Mouser, and Newark are all on backorder for the Hirose DM3D-SF SD card socket in the Rev 3 design.

If a Rev4 board is produced, adjust the footprint to allow for an alternate socket (such as the Molex 1051620001) to be used.
[It looks like the Molex could be made to fit on the same pads IFF the keep-out areas are increased and a second card-det landing is added.]

**Comment by sebsch2000** [comment]
Amphenol 114-00841-68 has the same footprint as the Hirose part. Right now Mouser has 4.813 of them in stock (Mouser part no. 523-114-00841-68).

**Comment by jackrubin** [comment]
Who’s on first? Does this mean that there is no need for a Rev 4 board spin and I can build out one of your Rev 3 sets?

Thanks,
Jack

**Comment by sebsch2000** [comment]
Well, I built a rev 3 board this week. I ordered the parts from Mouser and Digikey. Had to replace the Hirose connector with the Amphenol one and the ICL3232CPZ (U12) with the MAX232N which is basically the same. The test programs worked as they should.

**Comment by jackrubin** [comment]
That’s good – if you still have a spare, I’d like to buy one board + programmer set from you. Please let me know the cost and PayPal info.

Thanks,
Jack

**Comment by johnwinans** [comment]
How did I not find the Amphenol 114-00841-68 part????  That is fantastic!
I'll add a note marking that as an alternate and take a pass on the footprint hacking.

**Comment by jackrubin** [comment]
Please push the rev/bom changes up to the github repository when you get a chance.
Thanks!

**Comment by johnwinans** [comment]
There is at least one alternate that does not require a footprint modification.  I am not going to leave well enough alone.
